services:
  - type: web
    name: apnastay-api
    runtime: python
    rootDir: backend
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_NAME
        value: ApnaStay API
      - key: APP_ENV
        value: production
      - key: FIREBASE_PROJECT_ID
        value: urbanpg-a7198
      - key: FIREBASE_SERVICE_ACCOUNT_B64
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
      - key: DEV_AUTH_ENABLED
        value: "false"
      - key: ADMIN_ALLOWED_EMAILS
        value: "ashrafmaliknadaf5@gmail.com,ranjanrishabh2004@gmail.com,rishabhl.23.beis@acharya.ac.in,ashrafbusiness05@gmail.com"
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
